### ISSUE TITLE
[功能请求]增加保存账号功能

### ISSUE THREAD

**Issue by cui8** [CaoYunzhou/openai-billing#3]
这个项目太完美了，使用后非常棒👍。
但是，希望作者能继续完善。
比如：增加一个简单的账号密码登录，在后台有一个保存需要查询余额的账号功能。前端页面显示账号余额等信息，不要显示账号密码。

非常非常非常非常非常非常非常非常……希望作者能实现此功能。

最后，感谢作者在百忙中抽出时间编写出此项目，辛苦了，大佬。

**Comment by CaoYunzhou** [comment]
可以自己改代码，其他功能太多余的，这个就只是用来方便批量查询余额的
